name: Setup
description: Installs tooling and dependencies of repository
runs:
  using: composite
  steps:
    - name: Setup pnpm
      uses: pnpm/action-setup@a7487c7e89a18df4991f7f222e4898a00d66ddda # v4.1.0
    - name: Setup Node.js
      uses: actions/setup-node@cdca7365b2dadb8aad0a33bc7601856ffabcc48e # v4
      with:
        cache: pnpm
        node-version-file: .node-version
    - name: Install dependencies
      shell: bash
      run: cd .ci && make install
