name: Setup
description: Installs tooling and dependencies of repository
runs:
  using: composite
  steps:
    - name: Setup pnpm
      uses: pnpm/action-setup@fe02b34f77f8bc703788d5817da081398fad5dd2 # v4.0.0
    - name: Setup Node.js
      uses: actions/setup-node@39370e3970a6d050c480ffad4ff0ed4d3fdee5af # v4
      with:
        cache: pnpm
        node-version-file: .node-version
    - name: Install dependencies
      shell: bash
      run: cd .ci && make install
