name: Setup
description: Checks out the repository and installs tooling
runs:
  using: 'composite'
  steps:
    - name: Setup pnpm
      uses: pnpm/action-setup@v2
    - name: Setup Node.js
      uses: actions/setup-node@b39b52d1213e96004bfcb1c61a8a6fa8ab84f3e8 # v4
      with:
        cache: 'pnpm'
        node-version-file: '.node-version'
    - name: Install dependencies
      shell: bash
      run: cd .ci && make install
