coverage:
  status:
    patch:
      default:
        threshold: 5%
    project:
      default:
        threshold: 5%
comment:
  hide_project_coverage: false

codecov:
  notify:
    # 👇 Must be in sync with number of uploads needed.
    #    Which now depends on amount of E2E tests run
    #    Plus the unit tests coverage
    after_n_builds: 5
