name: Configuration
description: Loads GitHub Actions CI/CD pipelines (workflows) configuration
outputs:
  ng-cli-version-aliases:
    description: Angular CLI version aliases (from `angular-cli-versions.json` file) to generate example apps for
    value: ${{ steps.ng-cli-version-aliases.outputs.result }}
runs:
  using: composite
  steps:
    - name: Load available example apps Angular CLI version aliases
      uses: actions/github-script@f28e40c7f34bde8b3046d885e986cb6290c5673b # v7
      id: ng-cli-version-aliases
      with:
        script: |
          const angularCliVersions = require('./projects/ngx-meta/example-apps/angular-cli-versions.json')
          return Object.keys(angularCliVersions.devDependencies)
