export { CoreModule as NgxMetaCoreModule } from './src/core.module'
export * from './src/base-metadata'
export * from './src/composable-meta-property'
export * from './src/global-metadata'
export * from './src/global-metadata-definition'
export * from './src/global-metadata-image'
export * from './src/global-metadata-key'
export { makeForRootGuard as _makeForRootGuard } from './src/make-for-root-guard'
export * from './src/meta-content'
export * from './src/meta-property'
export * from './src/meta.service'
export * from './src/metadata'
export * from './src/metadata-definition'
export * from './src/metadata-values'
export * from './src/metadata.service'
export * from './src/provide-metadata'
export * from './src/scoped-metadata'
export * from './src/string-key-of'
