export { CoreModule as NgxMetaCoreModule } from './src/core.module'
export { FlatType as _FlatType } from './src/flat-type'
export * from './src/global-metadata'
export { makeForRootGuard as _makeForRootGuard } from './src/make-for-root-guard'
export * from './src/meta-content'
export * from './src/meta-property'
export * from './src/meta.service'
export * from './src/metadata'
export * from './src/metadata.service'
export * from './src/metadata-values'
export * from './src/scoped-metadata'
