export { StandardModule as NgxMetaStandardModule } from './src/standard.module'
export * from './src/html-lang-attribute/html-lang-attribute.service'
export * from './src/link-rel-canonical/link-rel-canonical.service'
// Specific metadata
export * from './src/title-standard-metadata.service'
export * from './src/description-standard-metadata.service'
export * from './src/author-standard-metadata.service'
export * from './src/keywords-standard-metadata.service'
export * from './src/generator-standard-metadata.service'
export * from './src/application-name-standard-metadata.service'
export * from './src/canonical-url-standard-metadata.service'
export * from './src/locale-standard-metadata.service'
