export { StandardModule as NgxMetaStandardModule } from './src/standard.module'
export * from './src/html-lang-attribute/html-lang-attribute.service'
export * from './src/link-rel-canonical/link-rel-canonical.service'
export * from './src/application-name-metadata'
export * from './src/author-metadata'
export * from './src/canonical-url-metadata'
export * from './src/description-metadata'
export * from './src/generator-metadata'
export * from './src/keywords-metadata'
export * from './src/title-metadata'
