export { StandardModule as NgxMetaStandardModule } from './src/standard.module'
export { provideStandard as provideNgxMetaStandardMetadata } from './src/provide-standard'
export * from './src/standard-metadata'
// Specific providers
export * from './src/standard-title-metadata-provider'
export * from './src/standard-description-metadata-provider'
export * from './src/standard-author-metadata-provider'
export * from './src/standard-keywords-metadata-provider'
export * from './src/standard-generator-metadata-provider'
export * from './src/standard-application-name-metadata-provider'
export * from './src/standard-canonical-url-metadata-provider'
export * from './src/standard-locale-metadata-provider'
