export { updateAppConfig } from './update-app-config.js'
export { updateAppModule } from './update-app-module.js'
export { updateMainToUseTypedAppComponent } from './update-main-to-use-typed-app-component.js'
export { STANDALONE_TEMPLATES_DIR } from './standalone-templates-dir.js'
export { MODULE_TEMPLATES_DIR } from './module-templates-dir.js'
