name: Push to main

on:
  push:
    branches: ['main']

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    name: Build
    uses: ./.github/workflows/reusable-build.yml
    with:
      dist-artifact-name: ngx-meta-dist
      tsc-artifact-name: ngx-meta-tsc
  test:
    name: Test
    uses: ./.github/workflows/reusable-test.yml
  lint:
    name: Lint
    uses: ./.github/workflows/reusable-lint.yml
  style:
    name: Style
    uses: ./.github/workflows/reusable-style.yml
  api-extractor:
    needs: [build]
    name: API Extractor
    uses: ./.github/workflows/reusable-api-extractor.yml
    with:
      tsc-artifact-name: ngx-meta-tsc
      api-docs-artifact-name: ngx-meta-api-docs
  e2e:
    needs: [build, test, lint]
    name: E2E
    uses: ./.github/workflows/reusable-e2e.yml
    with:
      dist-artifact-name: ngx-meta-dist
      e2e-app-artifact-name-prefix: ngx-meta-e2e-app-a
  bundle-size:
    needs: e2e
    name: Bundle size
    uses: ./.github/workflows/reusable-bundle-size.yml
    with:
      e2e-app-artifact-name-prefix: ngx-meta-e2e-app-a
      bundle-size-artifact-name-prefix: ngx-meta-bundle-size-a
    permissions:
      checks: write
  release:
    name: Release
    needs: [e2e]
    uses: ./.github/workflows/reusable-release.yml
    with:
      dist-artifact-name: ngx-meta-dist
    secrets:
      npm-token: ${{ secrets.NPM_TOKEN }}
      github-token-pr: ${{ secrets.PR_GH_TOKEN }}
    permissions:
      contents: write
      issues: write
      pull-requests: write
      id-token: write
  docs:
    name: Docs
    needs: [release, api-extractor, bundle-size]
    uses: ./.github/workflows/reusable-docs.yml
    with:
      api-docs-artifact-name: ngx-meta-api-docs
      bundle-size-artifact-name-prefix: ngx-meta-bundle-size-a
    secrets:
      cloudflare-account-id: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
      cloudflare-api-token: ${{ secrets.CLOUDFLARE_API_TOKEN }}
    permissions:
      deployments: write
