name: Push to main

on:
  push:
    branches: ['main']

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    name: Build
    uses: ./.github/workflows/reusable-build.yml
    with:
      artifact-name: build
  test:
    name: Test
    uses: ./.github/workflows/reusable-test.yml
  lint:
    name: Lint
    uses: ./.github/workflows/reusable-lint.yml
  style:
    name: Style
    uses: ./.github/workflows/reusable-style.yml
  release:
    name: Release
    needs: [build, test, lint]
    uses: ./.github/workflows/reusable-release.yml
    with:
      build-artifact-name: build
    secrets:
      npm-token: ${{ secrets.NPM_TOKEN }}
      github-token-pr: ${{ secrets.PR_GH_TOKEN }}
    permissions:
      contents: write
      issues: write
      pull-requests: write
      id-token: write
