name: Push to main

on:
  push:
    branches: ['main']

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    name: Build
    uses: ./.github/workflows/reusable-build.yml
  test:
    name: Test
    uses: ./.github/workflows/reusable-test.yml
  lint:
    name: Lint
    uses: ./.github/workflows/reusable-lint.yml
  style:
    name: Style
    uses: ./.github/workflows/reusable-style.yml
  api-extractor:
    needs: build
    name: API Extractor
    uses: ./.github/workflows/reusable-api-extractor.yml
  example-apps:
    needs: build
    name: Example apps
    uses: ./.github/workflows/reusable-example-apps.yml
  e2e:
    needs: example-apps
    name: E2E
    uses: ./.github/workflows/reusable-e2e.yml
  coverage:
    needs: [e2e, test]
    name: Coverage
    uses: ./.github/workflows/reusable-coverage.yml
    secrets:
      codecov-token: ${{ secrets.CODECOV_TOKEN }}
  bundle-size:
    needs: example-apps
    name: Bundle size
    uses: ./.github/workflows/reusable-bundle-size.yml
    permissions:
      checks: write
  release:
    name: Release
    needs: e2e
    uses: ./.github/workflows/reusable-release.yml
    secrets:
      npm-token: ${{ secrets.NPM_TOKEN }}
      github-token-pr: ${{ secrets.PR_GH_TOKEN }}
    permissions:
      contents: write
      issues: write
      pull-requests: write
      id-token: write
  docs:
    name: Docs
    needs: [api-extractor, bundle-size]
    uses: ./.github/workflows/reusable-docs.yml
    secrets:
      cloudflare-account-id: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
      cloudflare-api-token: ${{ secrets.CLOUDFLARE_API_TOKEN }}
    permissions:
      deployments: write
