name: Push to main

on:
  push:
    branches: ['main']

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    name: Build
    uses: ./.github/workflows/reusable-build.yml
    with:
      artifact-name: ngx-meta
  test:
    name: Test
    uses: ./.github/workflows/reusable-test.yml
  lint:
    name: Lint
    uses: ./.github/workflows/reusable-lint.yml
  style:
    name: Style
    uses: ./.github/workflows/reusable-style.yml
  e2e:
    needs: [build, test, lint]
    name: E2E
    uses: ./.github/workflows/reusable-e2e.yml
    with:
      build-artifact-name: ngx-meta
  release:
    name: Release
    needs: [e2e]
    uses: ./.github/workflows/reusable-release.yml
    with:
      build-artifact-name: ngx-meta
    secrets:
      npm-token: ${{ secrets.NPM_TOKEN }}
      github-token-pr: ${{ secrets.PR_GH_TOKEN }}
    permissions:
      contents: write
      issues: write
      pull-requests: write
      id-token: write
