name: Pull request

on:
  pull_request:

jobs:
  build:
    name: Build
    uses: ./.github/workflows/reusable-build.yml
  test:
    name: Test
    uses: ./.github/workflows/reusable-test.yml
  lint:
    name: Lint
    uses: ./.github/workflows/reusable-lint.yml
  style:
    name: Style
    uses: ./.github/workflows/reusable-style.yml
