name: Pull request

on:
  pull_request:

jobs:
  build:
    name: Build
    uses: ./.github/workflows/reusable-build.yml
    with:
      dist-artifact-name: ngx-meta-dist
      tsc-artifact-name: ngx-meta-tsc
  test:
    name: Test
    uses: ./.github/workflows/reusable-test.yml
  lint:
    name: Lint
    uses: ./.github/workflows/reusable-lint.yml
  style:
    name: Style
    uses: ./.github/workflows/reusable-style.yml
  api-extractor:
    name: API Extractor
    uses: ./.github/workflows/reusable-api-extractor.yml
    with:
      tsc-artifact-name: ngx-meta-tsc
      api-extractor-artifact-name: ngx-meta-api-extractor
  e2e:
    needs: [build, test, lint]
    name: E2E
    uses: ./.github/workflows/reusable-e2e.yml
    with:
      dist-artifact-name: ngx-meta-dist
    permissions:
      pull-requests: write
  docs:
    name: Docs
    uses: ./.github/workflows/reusable-docs.yml
    secrets:
      cloudflare-account-id: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
      cloudflare-api-token: ${{ secrets.CLOUDFLARE_API_TOKEN }}
    permissions:
      deployments: write
