name: Pull request

on:
  pull_request:

jobs:
  build:
    name: Build
    uses: ./.github/workflows/reusable-build.yml
    with:
      artifact-name: ngx-meta
  # Temporary for testing
  #test:
  #  name: Test
  #  uses: ./.github/workflows/reusable-test.yml
  lint:
    name: Lint
    uses: ./.github/workflows/reusable-lint.yml
  style:
    name: Style
    uses: ./.github/workflows/reusable-style.yml
  e2e:
    needs: [build, lint]
    name: E2E
    uses: ./.github/workflows/reusable-e2e.yml
    with:
      build-artifact-name: ngx-meta
    permissions:
      pull-requests: write
      # Temporary! Just to check now
      checks: write
