name: Test
on:
  workflow_call:

env:
  COVERAGE_DIR: coverage/ngx-meta
  # 👇 Keep in sync with e2e and coverage workflows
  COVERAGE_REPORT_ARTIFACT_NAME_SUFFIX: -coverage-report

permissions:
  contents: none

jobs:
  unit-test-libs:
    name: Unit tests (libs)
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
      - name: Setup
        uses: ./.github/actions/setup
      - name: Run unit tests
        run: cd .ci && make unit-test-libs
      - name: Upload coverage report
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7
        if: failure() || success()
        with:
          name: ngx-meta-unit-test${{ env.COVERAGE_REPORT_ARTIFACT_NAME_SUFFIX }}
          path: ${{ env.COVERAGE_DIR }}/*.json
          retention-days: 5

  unit-test-schematics:
    name: Unit tests (schematics)
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
      - name: Setup
        uses: ./.github/actions/setup
      - name: Run unit tests
        run: pnpm run test:unit:schematics:coverage
      - name: Upload coverage report
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7
        if: failure() || success()
        with:
          name: unit-test-schematics${{ env.COVERAGE_REPORT_ARTIFACT_NAME_SUFFIX }}
          path: coverage/jest/*.json
          retention-days: 5
