name: Docs
on:
  workflow_call:
    secrets:
      cloudflare-account-id:
        required: true
      cloudflare-api-token:
        required: true

env:
  DOCS_DIR: projects/ngx-meta/docs
  # 👇 Keep in sync with API Extractor workflow
  API_DOCS_ARTIFACT_NAME_SUFFIX: -api-docs
  # 👇 Keep in sync with pull request completed workflow
  BUNDLE_SIZE_ARTIFACT_NAME_SUFFIX: -bundle-size

permissions:
  contents: none

jobs:
  docs:
    name: Docs build & deploy
    defaults:
      run:
        working-directory: ${{ env.DOCS_DIR }}
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      deployments: write
    steps:
      - name: Checkout
        uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.1.0
      - name: Download API reference docs
        uses: actions/download-artifact@37930b1c2abaa49bbe596cd826c3c89aef350131 # v7.0.0
        with:
          name: ngx-meta${{ env.API_DOCS_ARTIFACT_NAME_SUFFIX }}
          path: projects/ngx-meta/docs/content/api
      - name: Download bundle size info
        uses: actions/download-artifact@37930b1c2abaa49bbe596cd826c3c89aef350131 # v7.0.0
        with:
          pattern: ngx-meta${{ env.BUNDLE_SIZE_ARTIFACT_NAME_SUFFIX }}*
      - name: Copy reports into directories
        working-directory: .
        run: |
          # shellcheck disable=SC2001
          for artifact_dir in "ngx-meta${{ env.BUNDLE_SIZE_ARTIFACT_NAME_PREFIX }}"*; do
            app_name="$(echo "$artifact_dir" | sed "s/^ngx-meta${{ env.BUNDLE_SIZE_ARTIFACT_NAME_SUFFIX }}-//")"
            bundle_size_app_dir="projects/ngx-meta/bundle-size/out/$app_name"
            mkdir -p "$bundle_size_app_dir"
            cp "$artifact_dir/bundle-size-report.md" "$bundle_size_app_dir"
          done
      - name: Install poetry # pipx comes built-in in GitHub runner
        run: pipx install poetry
      - name: Setup Python
        uses: actions/setup-python@ece7cb06caefa5fff74198d8649806c4678c61a1 # v6.3.0
        with:
          python-version-file: ${{ env.DOCS_DIR }}/pyproject.toml
          cache: poetry
          cache-dependency-path: ${{ env.DOCS_DIR }}/poetry.lock
      - name: Setup pnpm
        uses: pnpm/action-setup@fc06bc1257f339d1d5d8b3a19a8cae5388b55320 # v4.4.0
      - name: Setup Node.js
        uses: actions/setup-node@249970729cb0ef3589644e2896645e5dc5ba9c38 # v6.5.0
        with:
          cache: pnpm
          cache-dependency-path: ${{ env.DOCS_DIR }}/pnpm-lock.yaml
          node-version-file: .node-version
      - name: Install deps
        run: make setup
      - name: Generate cache id for Mkdocs build
        run: echo "cache_id=$(date --utc '+%V')" >> "$GITHUB_ENV"
      - name: Cache Mkdocs build
        uses: actions/cache@caa296126883cff596d87d8935842f9db880ef25 # v5.1.0
        with:
          key: mkdocs-material-${{ env.cache_id }}
          path: ${{ env.DOCS_DIR }}/.cache
          restore-keys: |
            mkdocs-material-
      - name: Build
        run: make build
      - name: Publish
        if: |
          (github.event_name == 'push' && github.ref_name == 'main') ||
          (
            github.event_name == 'pull_request' &&
            contains(github.event.pull_request.labels.*.name, 'preview docs')
          )
        uses: cloudflare/wrangler-action@9acf94ace14e7dc412b076f2c5c20b8ce93c79cd # v3.15.0
        with:
          accountId: ${{ secrets.cloudflare-account-id }}
          apiToken: ${{ secrets.cloudflare-api-token }}
          command: pages deploy site --project-name ngx-meta
          workingDirectory: ${{ env.DOCS_DIR }}
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
