name: E2E
on:
  workflow_call:
    inputs:
      ng-cli-version-aliases:
        type: string
        required: true

permissions:
  contents: none

env:
  E2E_DIR: projects/ngx-meta/e2e
  COVERAGE_DIR: coverage/ngx-meta
  # 👇 Keep in sync with the example apps workflow
  COVERAGE_ARTIFACT_NAME_SUFFIX: -coverage
  # 👇 Keep in sync with the example apps workflow
  EXAMPLE_APP_ARTIFACT_NAME_SUFFIX: -example-app
  # 👇 Keep in sync with e2e and coverage workflows
  COVERAGE_REPORT_ARTIFACT_NAME_SUFFIX: -coverage-report

jobs:
  e2e:
    name: E2E tests - Angular ${{ matrix.ng-cli-version-alias }}
    runs-on: ubuntu-latest
    timeout-minutes: 5
    strategy:
      matrix:
        ng-cli-version-alias: ${{ fromJSON(inputs.ng-cli-version-aliases) }}
    env:
      EXAMPLE_APP_DIR: projects/ngx-meta/example-apps/apps/${{ matrix.ng-cli-version-alias }}
    defaults:
      run:
        working-directory: ${{ env.E2E_DIR }}
    steps:
      - name: Checkout
        uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.1.0
      - name: Download example app with coverage instrumentation
        uses: actions/download-artifact@37930b1c2abaa49bbe596cd826c3c89aef350131 # v7.0.0
        with:
          name: ngx-meta${{ env.EXAMPLE_APP_ARTIFACT_NAME_SUFFIX }}-${{ matrix.ng-cli-version-alias }}${{ env.COVERAGE_ARTIFACT_NAME_SUFFIX }}
          path: ${{ env.EXAMPLE_APP_DIR }}
      - name: Setup pnpm
        uses: pnpm/action-setup@fc06bc1257f339d1d5d8b3a19a8cae5388b55320 # v4.4.0
      - name: Setup Node.js
        uses: actions/setup-node@249970729cb0ef3589644e2896645e5dc5ba9c38 # v6.5.0
        with:
          cache: pnpm
          cache-dependency-path: ${{ env.E2E_DIR }}/pnpm-lock.yaml
          node-version-file: .node-version # should be one compatible with Angular example app
      - name: Configure Cypress cache directory
        run: echo "CYPRESS_CACHE_FOLDER=$HOME/.cache/Cypress" >> "$GITHUB_ENV"
      - name: Cypress cache
        uses: actions/cache@caa296126883cff596d87d8935842f9db880ef25 # v5.1.0
        env:
          cache-name: ngx-meta-e2e-cypress
          e2e_lockfile_hash: ${{ hashFiles(format('{0}/pnpm-lock.yaml', env.E2E_DIR)) }}
        with:
          path: ${{ env.CYPRESS_CACHE_FOLDER }}
          key: ${{ env.cache-name }}-${{ env.e2e_lockfile_hash }}
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Serve app
        run: pnpm run ci:serve &
        working-directory: ${{ env.EXAMPLE_APP_DIR }}
      - name: Cypress run
        uses: cypress-io/github-action@f790eee7a50d9505912f50c2095510be7de06aa7 # v6.10.9
        env:
          COVERAGE_JSON_REPORT_NAME: e2e-${{ matrix.ng-cli-version-alias }}.json
        with:
          working-directory: ${{ env.E2E_DIR }}
          browser: chrome
          # 👇 Action doesn't support pnpm caching right now
          # https://github.com/cypress-io/github-action/tree/v6.6.1?tab=readme-ov-file#pnpm
          # Given we're doing caching manually, installing apart to leverage cache
          install: false
      - name: Upload coverage report
        uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f # v6.0.0
        if: failure() || success()
        with:
          name: ngx-meta-e2e-${{ matrix.ng-cli-version-alias }}${{ env.COVERAGE_REPORT_ARTIFACT_NAME_SUFFIX }}
          path: ${{ env.COVERAGE_DIR }}/*.json
          retention-days: 5
