name: API Extractor
on:
  workflow_call:

env:
  # 👇 Keep in sync with the build workflow
  TSC_ARTIFACT_NAME_SUFFIX: -tsc
  # 👇 Keep in sync with docs workflow
  API_DOCS_ARTIFACT_NAME_SUFFIX: -api-docs

permissions:
  contents: none

jobs:
  api-extractor:
    name: API Extractor
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
      - name: Download tsc output files
        uses: actions/download-artifact@9000827ccba6bdab643e8b6fd33ac0654aef8333 # v8
        with:
          name: ngx-meta${{ env.TSC_ARTIFACT_NAME_SUFFIX }}
          path: projects/ngx-meta/out
      - name: Setup
        uses: ./.github/actions/setup
      - name: Run API Extractor in production mode
        run: pnpm run ngx-meta:api-extractor
      - name: Run API Documenter
        run: pnpm run ngx-meta:api-documenter
      - name: Upload API Documenter generated Markdown docs
        uses: actions/upload-artifact@cf430e030ddbb5b0abf93d22962f4752f3646cd9 # v7
        with:
          name: ngx-meta${{ env.API_DOCS_ARTIFACT_NAME_SUFFIX }}
          path: projects/ngx-meta/docs/content/api
          retention-days: 5
