name: E2E
on:
  workflow_call:
    inputs:
      ng-cli-version-aliases:
        type: string
        required: true

permissions:
  contents: none

env:
  E2E_DIR: projects/ngx-meta/e2e
  COVERAGE_DIR: coverage/ngx-meta
  # 👇 Keep in sync with the example apps workflow
  COVERAGE_ARTIFACT_NAME_SUFFIX: -coverage
  # 👇 Keep in sync with the example apps workflow
  EXAMPLE_APP_ARTIFACT_NAME_SUFFIX: -example-app
  # 👇 Keep in sync with e2e and coverage workflows
  COVERAGE_REPORT_ARTIFACT_NAME_SUFFIX: -coverage-report

jobs:
  e2e:
    name: E2E tests - Angular ${{ matrix.ng-cli-version-alias }}
    runs-on: ubuntu-latest
    timeout-minutes: 5
    strategy:
      matrix:
        ng-cli-version-alias: ${{ fromJSON(inputs.ng-cli-version-aliases) }}
    env:
      EXAMPLE_APP_DIR: projects/ngx-meta/example-apps/apps/${{ matrix.ng-cli-version-alias }}
    defaults:
      run:
        working-directory: ${{ env.E2E_DIR }}
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
      - name: Download example app with coverage instrumentation
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8
        with:
          name: ngx-meta${{ env.EXAMPLE_APP_ARTIFACT_NAME_SUFFIX }}-${{ matrix.ng-cli-version-alias }}${{ env.COVERAGE_ARTIFACT_NAME_SUFFIX }}
          path: ${{ env.EXAMPLE_APP_DIR }}
      - name: Setup pnpm
        uses: pnpm/action-setup@ea17c68df8912ef543352723c149a84f56e3d413 # v6.1.0
      - name: Setup Node.js
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7
        with:
          cache: pnpm
          cache-dependency-path: ${{ env.E2E_DIR }}/pnpm-lock.yaml
          node-version-file: .node-version # should be one compatible with Angular example app
      - name: Configure Cypress cache directory
        run: echo "CYPRESS_CACHE_FOLDER=$HOME/.cache/Cypress" >> "$GITHUB_ENV"
      - name: Cypress cache
        uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6
        env:
          cache-name: ngx-meta-e2e-cypress
          e2e_lockfile_hash: ${{ hashFiles(format('{0}/pnpm-lock.yaml', env.E2E_DIR)) }}
        with:
          path: ${{ env.CYPRESS_CACHE_FOLDER }}
          key: ${{ env.cache-name }}-${{ env.e2e_lockfile_hash }}
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Serve app
        run: pnpm run ci:serve &
        working-directory: ${{ env.EXAMPLE_APP_DIR }}
      - name: Cypress run
        uses: cypress-io/github-action@09090944bd8aaa2a517cefb6e38bf1aae336b42b # v7.4.3
        env:
          COVERAGE_JSON_REPORT_NAME: e2e-${{ matrix.ng-cli-version-alias }}.json
        with:
          working-directory: ${{ env.E2E_DIR }}
          browser: chrome
          # 👇 Action doesn't support pnpm caching right now
          # https://github.com/cypress-io/github-action/tree/v6.6.1?tab=readme-ov-file#pnpm
          # Given we're doing caching manually, installing apart to leverage cache
          install: false
      - name: Upload coverage report
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7
        if: failure() || success()
        with:
          name: ngx-meta-e2e-${{ matrix.ng-cli-version-alias }}${{ env.COVERAGE_REPORT_ARTIFACT_NAME_SUFFIX }}
          path: ${{ env.COVERAGE_DIR }}/*.json
          retention-days: 5
