site_name: ngx-meta docs
site_url: https://ngx-meta.pages.dev
repo_url: https://github.com/davidlj95/ngx
site_description: >
  Set your Angular site's metadata: `<meta>`s, Open Graph, Twitter cards,
  JSON LD structured data & more. Use a service and/or route's data.
  Works with Angular SSR / Universal. Set it up now in a flash 🚀
site_author: davidlj95
copyright: MIT License
theme:
  name: material
docs_dir: content
site_dir: site
