site_name: '@davidlj95/ngx-meta'
site_url: https://ngx-meta.dev
repo_url: https://github.com/davidlj95/ngx
site_description: >
  Set your Angular site's metadata: standard meta tags, Open Graph,
  Twitter Cards, JSON-LD structured data and more.
  Supports SSR (and Angular Universal).
  Use a service. Use routes' data.
  Set it up in a flash! 🚀
site_author: davidlj95
copyright: MIT License
docs_dir: content
site_dir: site
edit_uri: https://github.com/davidlj95/ngx/edit/main/projects/ngx-meta/docs/content/
nav:
  - index.md
  - Why:
      - why/index.md
      - why/design-principles.md
      - why/features.md
      - why/comparison.md
  - get-started.md
  - Guides:
      - guides/set-metadata-using-service.md
      - guides/set-metadata-using-routing.md
      - guides/metadata-values-json.md
      - guides/defaults.md
      - guides/url-resolution.md
      - guides/late-loading-modules.md
      - guides/manage-your-custom-metadata.md
      - guides/custom-metadata-providers-selection.md
      - guides/manual-setup.md
  - Built-in modules:
      - Built-in modules: built-in-modules/index.md
      - built-in-modules/standard.md
      - built-in-modules/open-graph.md
      - built-in-modules/twitter-cards.md
      - built-in-modules/json-ld.md
  - API Reference: api/ngx-meta.md
  - changelog.md
  - Migrations:
      - migrations/01-meta-element-apis.md
      - migrations/03-const-to-function-manager-providers.md
  - Misc:
      - misc/example-apps.md
      - misc/bundle-size.md
      - misc/public-api-surface.md
      - misc/standalone-vs-module-apis.md
not_in_nav: api/*.md
# From here below, all for Material for mkdocs
repo_name: davidlj95/ngx
theme:
  name: material
  palette:
    # Palette toggle for light mode
    - media: '(prefers-color-scheme: light)'
      scheme: default
      primary: custom
      accent: custom
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    # Palette toggle for dark mode
    - media: '(prefers-color-scheme: dark)'
      scheme: slate
      primary: custom
      accent: custom
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  font: false
  language: en
  icon:
    logo: material/code-tags
    repo: fontawesome/brands/github
  favicon: images/favicon.png
  features:
    - navigation.instant
    - navigation.instant.progress
    - navigation.footer
    - navigation.tracking
    - navigation.indexes
    - toc.integrate
    - toc.follow
    - navigation.top
    - search.suggest
    - search.highlight
    - search.share
    - content.action.edit
    - content.action.view
    - content.tooltips
    - content.tabs.link
extra_css:
  - fonts/@fontsource-variable/inter-tight/index.css
  - fonts/@fontsource/dm-mono/index.css
  - stylesheets/extra.css
plugins:
  # Until we can ignore disabling badges
  #- privacy
  - search
  - autolinks
  - social:
      cards_layout_options:
        font_family: Inter Tight
  - git-revision-date-localized:
      type: timeago
extra:
  social:
    - name: ngx-meta on GitHub
      icon: fontawesome/brands/github
      link: https://github.com/davidlj95/ngx
    - name: ngx-meta on NPM
      icon: fontawesome/brands/npm
      link: https://www.npmjs.com/package/@davidlj95/ngx-meta
markdown_extensions:
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - abbr
  - pymdownx.snippets:
      auto_append:
        - includes/abbreviations.md
        - includes/common-links.md
  - footnotes
  - pymdownx.tabbed:
      alternate_style: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - pymdownx.critic
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - def_list
watch:
  - includes
